import mongoose from 'mongoose';
const { Schema, model } = mongoose;
const options = { timestamps: true, toJSON: { virtuals: true } };
const User = model('User', new Schema({ deletedAt:Date,vendor:{type:Schema.Types.ObjectId,ref:'User',index:true,immutable:true},vendorCode:{type:String,unique:true,sparse:true,immutable:true},fullName:{type:String,required:true,trim:true}, email:{type:String,unique:true,sparse:true,lowercase:true}, mobile:{type:String}, passwordHash:{type:String}, otpIdentity:{type:String,unique:true,sparse:true}, role:{type:String,enum:['candidate','admin','super_admin','reviewer','vendor'],default:'candidate'}, permissions:{type:[String],default:[]},status:{type:String,enum:['pending','verified','rejected','blocked'],default:'pending'}, recordingMode:{type:String,enum:['script','non_script'],default:'non_script'},refreshTokens:[String], resetToken:String, resetExpires:Date }, options));
const CandidateProfile = model('CandidateProfile', new Schema({ user:{type:Schema.Types.ObjectId,ref:'User',unique:true}, candidateId:{type:String,unique:true}, gender:String, state:String, city:String, nativeLanguages:[String], dialect:String, experience:String, deviceType:String, consent:{type:Boolean,default:false}, online:{type:Boolean,default:false}, earnings:{type:Number,default:0}, submittedSeconds:{type:Number,default:0} }, options));
const Project = model('Project', new Schema({ name:{type:String,required:true}, recordingType:{type:String,enum:['dual','single'],default:'dual'}, languages:[{language:String,dialects:[String]}], targetHours:Number, dailyTarget:Number, genderRule:{type:String,enum:['any','same','different'],default:'any'}, startDate:Date,endDate:Date,guidelines:String,consentText:String,active:{type:Boolean,default:true} }, options));
const Script = model('Script', new Schema({ topic:{type:Schema.Types.ObjectId,ref:'Topic'},project:{type:Schema.Types.ObjectId,ref:'Project',required:true}, language:String,dialect:String,title:String,content:String,usedBy:[{type:Schema.Types.ObjectId,ref:'User'}],active:{type:Boolean,default:true} }, options));
const PairingQueue = model('PairingQueue', new Schema({ user:{type:Schema.Types.ObjectId,ref:'User',unique:true}, project:{type:Schema.Types.ObjectId,ref:'Project'},language:String,dialect:String,recordingType:{type:String,default:'dual'},topic:{type:Schema.Types.ObjectId,ref:'Topic'},recordingMode:{type:String,enum:['script','non_script'],default:'script'},gender:String,availableAt:Date,status:{type:String,enum:['waiting','matched','paused'],default:'waiting'},socketId:String }, options));
const PairingMatch = model('PairingMatch', new Schema({ candidates:[{type:Schema.Types.ObjectId,ref:'User'}], project:{type:Schema.Types.ObjectId,ref:'Project'}, script:{type:Schema.Types.ObjectId,ref:'Script'},roomId:{type:String,unique:true},status:{type:String,enum:['pending','accepted','expired','declined','active','completed','cancelled'],default:'pending'},acceptedBy:[{type:Schema.Types.ObjectId,ref:'User'}],expiresAt:Date }, options));
const RecordingSession = model('RecordingSession', new Schema({ topic:{type:Schema.Types.ObjectId,ref:'Topic'},topicApprovedBy:[{type:Schema.Types.ObjectId,ref:'User'}],topicVersion:{type:Number,default:0},language:String,dialect:String,match:{type:Schema.Types.ObjectId,ref:'PairingMatch'},project:{type:Schema.Types.ObjectId,ref:'Project'},script:{type:Schema.Types.ObjectId,ref:'Script'},recordingMode:{type:String,enum:['script','non_script'],default:'script'},roomId:String,submissionRequestedAt:Date,submissionRequestedBy:{type:Schema.Types.ObjectId,ref:'User'},candidates:{type:[{type:Schema.Types.ObjectId,ref:'User'}],validate:{validator:ids=>ids.length===2&&String(ids[0])!==String(ids[1]),message:'A recording session requires exactly two different participants.'}},status:{type:String,enum:['waiting','recording','submitted','assigned','approved','rejected','revision'],default:'waiting'},consents:[{type:Schema.Types.ObjectId,ref:'User'}],controlState:{type:String,enum:['idle','recording','paused','stopped'],default:'idle'},controlVersion:{type:Number,default:0},controlElapsedMs:{type:Number,default:0},controlChangedAt:Date,controlMuted:{type:Boolean,default:false},startedAt:Date,endedAt:Date,duration:Number,metadata:Schema.Types.Mixed }, options));
const RecordingFile = model('RecordingFile', new Schema({ session:{type:Schema.Types.ObjectId,ref:'RecordingSession'},user:{type:Schema.Types.ObjectId,ref:'User'},channel:{type:String,enum:['speakerA','speakerB','mixed']},key:String,mimeType:String,size:Number }, options));
RecordingFile.schema.index({session:1,user:1},{unique:true});
const QCReview = model('QCReview', new Schema({ session:{type:Schema.Types.ObjectId,ref:'RecordingSession',unique:true},reviewer:{type:Schema.Types.ObjectId,ref:'User'},checklist:{language:Boolean,bothSpeakers:Boolean,noise:Boolean,script:Boolean,duration:Boolean,unique:Boolean},decision:{type:String,enum:['approved','rejected','revision']},reason:String,notes:String }, options));
const Notification = model('Notification',new Schema({user:{type:Schema.Types.ObjectId,ref:'User'},title:String,message:String,read:{type:Boolean,default:false}},options));
const AuditLog = model('AuditLog',new Schema({actor:{type:Schema.Types.ObjectId,ref:'User'},action:String,entity:String,entityId:String,details:Schema.Types.Mixed},options));
export { User,CandidateProfile,Project,Script,PairingQueue,PairingMatch,RecordingSession,RecordingFile,QCReview,Notification,AuditLog };

const OtpChallenge=model('OtpChallenge',new Schema({vendor:{type:Schema.Types.ObjectId,ref:'User'},identifier:{type:String,unique:true,required:true},challengeId:{type:String,unique:true,required:true},user:{type:Schema.Types.ObjectId,ref:'User'},codeHash:{type:String,required:true},attempts:{type:Number,default:0},sentAt:{type:Date,required:true},expiresAt:{type:Date,required:true,index:{expires:0}},delivered:{type:Boolean,default:false}}));
export {OtpChallenge};

const IntegrationSettings=model('IntegrationSettings',new Schema({name:{type:String,unique:true,required:true},config:{type:Schema.Types.Mixed,required:true},updatedBy:{type:Schema.Types.ObjectId,ref:'User'}},options));
export {IntegrationSettings};

const Topic=model('Topic',new Schema({name:{type:String,required:true,trim:true},key:{type:String,required:true,unique:true},enabled:{type:Boolean,default:true}},options));export {Topic};

const ReviewActivity=model('ReviewActivity',new Schema({session:{type:Schema.Types.ObjectId,ref:'RecordingSession',index:true},actor:{type:Schema.Types.ObjectId,ref:'User'},actorName:String,actorRole:String,location:String,action:{type:String,enum:['started','approved','rejected','revision']},startedAt:Date,durationSeconds:Number,notes:String,reason:String},options));
export {ReviewActivity};
