import 'express-async-errors';import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import jwt from 'jsonwebtoken';
import router from './profile-vendor-routes.js';import {User} from './models.js';
process.env.JWT_ACCESS_SECRET='profile-vendor-test';
test('candidate profile links an active vendor once; invalid codes, other roles and reassignment are denied',async()=>{
 const originals={findById:User.findById,findOne:User.findOne,update:User.collection.updateOne};const id='aaaaaaaaaaaaaaaaaaaaaaaa',vendorId='bbbbbbbbbbbbbbbbbbbbbbbb',otherId='cccccccccccccccccccccccc';let linked=null,writes=0,concurrent=false;
 User.findById=()=>({select:async()=>({role:'candidate',status:'verified',vendor:linked})});
 User.findOne=query=>({select:async()=>query.$or?query.$or[1]._id===vendorId?{_id:vendorId}:query.$or[1]._id===otherId?{_id:otherId}:null:{_id:vendorId,role:'vendor',fullName:'Vendor',vendorCode:'VND-'+vendorId.toUpperCase()}});
 User.collection.updateOne=async(filter,update)=>{assert.equal(String(filter._id),id);assert.equal(filter.vendor,null);assert.equal(filter.role,'candidate');if(concurrent){linked=otherId;return {matchedCount:0}}writes++;linked=String(update.$set.vendor);return {matchedCount:1}};
 const app=express();app.use(express.json());app.use(router);app.use((e,q,r,n)=>r.status(400).json({message:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const post=(vendorCode,role='candidate')=>fetch('http://127.0.0.1:'+server.address().port+'/me/vendor',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+jwt.sign({id,role},process.env.JWT_ACCESS_SECRET)},body:JSON.stringify({vendorCode})});
 try{assert.equal((await post('bad')).status,400);assert.equal((await post('VND-'+'d'.repeat(24))).status,400);assert.equal((await post('VND-'+vendorId,'vendor')).status,403);let response=await post('vnd-'+vendorId);assert.equal(response.status,200);assert.equal((await response.json()).vendor.fullName,'Vendor');assert.equal(linked,vendorId);assert.equal(writes,1);assert.equal((await post('VND-'+vendorId)).status,200);assert.equal(writes,1);assert.equal((await post('VND-'+otherId)).status,409);assert.equal(linked,vendorId);linked=null;concurrent=true;assert.equal((await post('VND-'+vendorId)).status,409);assert.equal(linked,otherId)}finally{User.findById=originals.findById;User.findOne=originals.findOne;User.collection.updateOne=originals.update;await new Promise(resolve=>server.close(resolve))}
});

test('vendor dashboard counts only its own candidates and participant dashboard shows persisted vendor link',async()=>{
 const originals={findById:User.findById,findOne:User.findOne,count:User.countDocuments};const candidateId='aaaaaaaaaaaaaaaaaaaaaaaa',vendorId='bbbbbbbbbbbbbbbbbbbbbbbb';let grant=true;
 User.findById=id=>({select:async()=>id===vendorId?{_id:vendorId,role:'vendor',status:'verified',fullName:'Vendor',vendorCode:'VND-'+vendorId.toUpperCase(),permissions:grant?['candidates.read']:[]}:{_id:candidateId,role:'candidate',status:'verified',vendor:vendorId}});
 User.findOne=q=>({select:async()=>{assert.equal(String(q._id),vendorId);return {_id:vendorId,fullName:'Vendor',role:'vendor',status:'verified'}}});User.countDocuments=async q=>{assert.deepEqual(q,{role:'candidate',vendor:vendorId});return 1};
 const app=express();app.use(router);const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const get=(path,role,id)=>fetch('http://127.0.0.1:'+server.address().port+path,{headers:{Authorization:'Bearer '+jwt.sign({role,id},process.env.JWT_ACCESS_SECRET)}});
 try{let response=await get('/dashboard/vendor?vendor=cccccccccccccccccccccccc','vendor',vendorId);assert.equal(response.status,200);let data=await response.json();assert.equal(data.candidateCount,1);assert.equal(data.canViewCandidates,true);grant=false;data=await (await get('/dashboard/vendor','vendor',vendorId)).json();assert.equal(data.canViewCandidates,false);data=await (await get('/me/vendor','candidate',candidateId)).json();assert.equal(data.vendor.vendorCode,'VND-'+vendorId.toUpperCase());assert.equal((await get('/dashboard/vendor','candidate',candidateId)).status,403);assert.equal((await get('/me/vendor','vendor',vendorId)).status,403)}finally{User.findById=originals.findById;User.findOne=originals.findOne;User.countDocuments=originals.count;await new Promise(resolve=>server.close(resolve))}
});
