import {S3Client,GetObjectCommand,PutObjectCommand,HeadObjectCommand,HeadBucketCommand} from '@aws-sdk/client-s3';import {getSignedUrl} from '@aws-sdk/s3-request-presigner';import {deliveryConfig} from './integration-settings.js';
export function r2Configured(config){return !!(config.R2_ACCOUNT_ID&&config.R2_BUCKET&&config.R2_ACCESS_KEY_ID&&config.R2_SECRET_ACCESS_KEY)}
export function storageOptions(config){if(config.R2_ACCOUNT_ID||config.R2_BUCKET){if(!r2Configured(config))throw Error('Cloudflare R2 is not configured. Ask your administrator to complete API Settings.');return {bucket:config.R2_BUCKET,options:{region:'auto',endpoint:'https://'+config.R2_ACCOUNT_ID+'.r2.cloudflarestorage.com',forcePathStyle:true,requestChecksumCalculation:'WHEN_REQUIRED',credentials:{accessKeyId:config.R2_ACCESS_KEY_ID,secretAccessKey:config.R2_SECRET_ACCESS_KEY}}}}if(!process.env.S3_BUCKET)throw Error('Recording storage is not configured. Ask your administrator to configure Cloudflare R2 in API Settings.');return {bucket:process.env.S3_BUCKET,options:{region:process.env.S3_REGION||'us-east-1',endpoint:process.env.S3_ENDPOINT||undefined,forcePathStyle:!!process.env.S3_ENDPOINT,requestChecksumCalculation:'WHEN_REQUIRED',credentials:process.env.S3_ACCESS_KEY_ID?{accessKeyId:process.env.S3_ACCESS_KEY_ID,secretAccessKey:process.env.S3_SECRET_ACCESS_KEY}:undefined}}}
async function storage(){const {bucket,options}=storageOptions(await deliveryConfig());return {bucket,client:new S3Client(options)}}
export async function signedUpload(key,contentType){const {bucket,client}=await storage();return getSignedUrl(client,new PutObjectCommand({Bucket:bucket,Key:key,ContentType:contentType}),{expiresIn:900})}
export async function signedDownload(key){const {bucket,client}=await storage();return getSignedUrl(client,new GetObjectCommand({Bucket:bucket,Key:key}),{expiresIn:900})}
export async function uploadedObject(key){const {bucket,client}=await storage();return client.send(new HeadObjectCommand({Bucket:bucket,Key:key}))}
export async function testStorage(config){if(!r2Configured(config))throw Error('Save complete R2 settings before testing.');const {bucket,options}=storageOptions(config);await new S3Client(options).send(new HeadBucketCommand({Bucket:bucket}))}

export async function uploadRecording(key,contentType,body,size,signal){const {bucket,client}=await storage();try{return await client.send(new PutObjectCommand({Bucket:bucket,Key:key,ContentType:contentType,ContentLength:size,Body:body}),{abortSignal:signal})}finally{client.destroy()}}
