import React,{useState,useEffect,useRef} from 'react';
import {api} from './api';
import useWorkspaceRefresh from './useWorkspaceRefresh';
import {permissionOptions,togglePermission} from './permissions';
export default function AccessControl(){
 const [search,setSearch]=useState(''),[roleFilter,setRoleFilter]=useState(''),[statusFilter,setStatusFilter]=useState('');const version=useRef(0);
 const [rows,setRows]=useState([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[busy,setBusy]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(next=page){const current=++version.current;const response=await api.get('/admin/access-control',{params:{page:next,...(search?{search}:{}),...(roleFilter?{role:roleFilter}:{}),...(statusFilter?{status:statusFilter}:{})}});if(current!==version.current)return;setRows(response.data.items);setTotal(response.data.total);setPage(next)}
 useWorkspaceRefresh(()=>load().catch(()=>setError('Unable to load account access. Use Refresh.')));
 useEffect(()=>{const timer=setTimeout(()=>load(1).catch(()=>setError('Unable to search accounts.')),250);return()=>{clearTimeout(timer);version.current++}},[search,roleFilter,statusFilter]);
 const change=(id,field,value)=>setRows(previous=>previous.map(row=>row._id===id?{...row,[field]:value}:row));
 async function save(row){setBusy(row._id);setError('');setMessage('');try{const response=await api.patch('/admin/access-control/'+row._id,{permissions:row.permissions,status:row.status==='blocked'?'blocked':'verified'});setRows(previous=>previous.map(item=>item._id===row._id?response.data.user:item));setMessage('Access saved for '+row.fullName+'. Changes apply immediately.')}catch(e){setError(e.response?.data?.message||'Unable to save access.')}finally{setBusy(null)}}
 return <div><p className="participant-kicker">OPERATIONS WORKSPACE</p><h1 className="text-2xl font-bold mt-2 mb-2">Access control</h1><p className="text-sm text-slate-500 mb-5">Choose access for each Vendor and QA account.</p><div className="card p-4 mb-5 flex flex-wrap gap-3"><input className="field" style={{maxWidth:350}} aria-label="Search account access" placeholder="Search name, email or code" value={search} onChange={e=>setSearch(e.target.value)}/><select className="field" style={{maxWidth:180}} aria-label="Filter role" value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="">All roles</option><option value="vendor">Vendor</option><option value="reviewer">QA</option></select><select className="field" style={{maxWidth:180}} aria-label="Filter status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option><option value="verified">Active</option><option value="blocked">Blocked</option></select><button className="btn-secondary" onClick={()=>{setSearch('');setRoleFilter('');setStatusFilter('')}}>Clear filters</button></div>{error&&<p role="alert" className="participant-error">{error}</p>}{message&&<p role="status" className="text-sm text-emerald-700 mb-4">{message}</p>}{rows.map(row=><section className="card p-5 mb-4" key={row._id}><fieldset disabled={busy===row._id}><div className="flex flex-wrap justify-between gap-3 mb-4"><div><h2 className="font-bold">{row.fullName}</h2>{row.vendorCode&&<p className="text-xs font-mono mt-1">{row.vendorCode}</p>}<p className="text-sm text-slate-500">{row.email} / {row.role==='reviewer'?'QA':'Vendor'}</p></div><label className="text-sm">Account status <select className="rounded-lg border p-2 ml-2" value={row.status==='blocked'?'blocked':'verified'} onChange={e=>change(row._id,'status',e.target.value)}><option value="verified">Active</option><option value="blocked">Blocked</option></select></label></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{permissionOptions.map(([key,label])=><label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={row.permissions?.includes(key)||false} onChange={e=>change(row._id,'permissions',togglePermission(row.permissions||[],key,e.target.checked))}/>{label}</label>)}</div><button className="btn-primary mt-4" onClick={()=>save(row)}>{busy===row._id?'Saving...':'Save access'}</button></fieldset></section>)}{!rows.length&&<p className="card p-6 text-sm text-slate-500">Create Vendor or QA accounts to configure access.</p>}{total>50&&<div className="flex gap-4 items-center"><button className="btn-secondary" disabled={page===1} onClick={()=>load(page-1).catch(()=>setError('Unable to load accounts.'))}>Previous</button><span>Page {page}</span><button className="btn-secondary" disabled={page*50>=total} onClick={()=>load(page+1).catch(()=>setError('Unable to load accounts.'))}>Next</button></div>}</div>
}
