import BrandLogo from './BrandLogo';
import AccountMenu from './AccountMenu';
import React,{useState,useEffect} from 'react';
import {NavLink,useLocation} from 'react-router-dom';
import {Mic,LayoutDashboard,Users,ClipboardCheck,LogOut,Menu,X,ChevronRight,ShieldCheck,Settings,FileText,RefreshCw} from 'lucide-react';
const sections=[
 {label:'OVERVIEW',links:[{to:'/',label:'Dashboard',icon:LayoutDashboard}]},
 {label:'PEOPLE & TEAMS',links:[{to:'/admin/candidates',label:'Candidates',icon:Users},{to:'/admin/vendors',label:'Vendors',icon:Users},{to:'/admin/quality-team',label:'Quality team',icon:ClipboardCheck}]},
 {label:'CONTENT LIBRARY',links:[{to:'/admin/projects',label:'Projects, languages & dialects',icon:FileText},{to:'/admin/topics',label:'Topics',icon:FileText},{to:'/admin/scripts',label:'Scripts',icon:FileText}]},
 {label:'QUALITY',links:[{to:'/admin/reviews',label:'Quality reviews',icon:ClipboardCheck}]},
 {label:'SETTINGS & ACCESS',links:[{to:'/admin/access-control',label:'Access control',icon:ShieldCheck},{to:'/admin/api-settings',label:'API Settings',icon:Settings,superAdminOnly:true}]}
];
export default function AdminShell({user,logout,onUserUpdate,children}){
 useEffect(()=>{document.documentElement.classList.toggle('compact-workspace',localStorage.getItem('compactWorkspace:'+user._id)==='true');return()=>document.documentElement.classList.remove('compact-workspace')},[user._id]);
 const[refreshing,setRefreshing]=useState(false);async function refresh(){if(refreshing)return;setRefreshing(true);try{const detail={tasks:[]};window.dispatchEvent(new CustomEvent('workspace:refresh',{detail}));await Promise.allSettled(detail.tasks)}finally{setRefreshing(false)}}
 const[open,setOpen]=useState(false);const location=useLocation();const role=user.role==='super_admin'?'Super Admin':'Admin';const groups=sections.map(section=>({...section,links:section.links.filter(link=>!link.superAdminOnly||user.role==='super_admin')}));const navigation=groups.flatMap(section=>section.links);const current=navigation.find(x=>x.to===location.pathname)?.label||'Workspace';
 return <div className="admin-shell">{open&&<button className="admin-backdrop" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside className={`admin-sidebar ${open?'is-open':''}`}><div className="admin-brand"><div className="admin-brand-image"><BrandLogo/></div><button className="admin-mobile-close" aria-label="Close navigation" onClick={()=>setOpen(false)}><X size={20}/></button></div><nav className="admin-section-nav" aria-label="Admin navigation">{groups.map(section=><section className="admin-nav-section" key={section.label} aria-label={section.label}><h2 className="admin-nav-label">{section.label}</h2>{section.links.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)} className={({isActive})=>`admin-nav-link ${isActive?'active':''}`}><Icon size={19}/><span>{label}</span><ChevronRight size={15}/></NavLink>)}</section>)}</nav></aside><div className="admin-body"><header className="admin-topbar"><div className="admin-breadcrumb"><button className="admin-menu" aria-label="Open navigation" aria-expanded={open} onClick={()=>setOpen(!open)}><Menu size={21}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{current}</strong></div><div className="admin-topbar-account"><button className="workspace-refresh" disabled={refreshing} onClick={refresh} aria-label="Refresh page data"><RefreshCw size={17} className={refreshing?'refresh-spinning':''}/><span>{refreshing?'Refreshing...':'Refresh'}</span></button><span className="admin-role">{role}</span><div className="admin-topbar-user"><strong>{user.fullName}</strong><small>{user.email}</small></div><AccountMenu user={user} logout={logout} onUserUpdate={onUserUpdate}/></div></header><main className="admin-content">{children}</main></div></div>;
}
