import BrandLogo from './BrandLogo';
import AccountMenu from './AccountMenu';
import React,{useState,useEffect} from 'react';
import {NavLink,useLocation} from 'react-router-dom';
import {Mic,LayoutDashboard,Users,ClipboardCheck,LogOut,Menu,X,ChevronRight,ShieldCheck,Settings,FileText,RefreshCw} from 'lucide-react';
const links=[{to:'/',label:'Dashboard',icon:LayoutDashboard},{to:'/admin/candidates',label:'Candidates',icon:Users},{to:'/admin/topics',label:'Topics',icon:FileText},{to:'/admin/scripts',label:'Scripts',icon:FileText},{to:'/admin/reviews',label:'Quality reviews',icon:ClipboardCheck}];
export default function AdminShell({user,logout,onUserUpdate,children}){
 useEffect(()=>{document.documentElement.classList.toggle('compact-workspace',localStorage.getItem('compactWorkspace:'+user._id)==='true');return()=>document.documentElement.classList.remove('compact-workspace')},[user._id]);
 const[refreshing,setRefreshing]=useState(false);async function refresh(){if(refreshing)return;setRefreshing(true);try{const detail={tasks:[]};window.dispatchEvent(new CustomEvent('workspace:refresh',{detail}));await Promise.allSettled(detail.tasks)}finally{setRefreshing(false)}}
 const[open,setOpen]=useState(false);const location=useLocation();const role=user.role==='super_admin'?'Super Admin':'Admin';const navigation=user.role==='super_admin'?[...links,{to:'/admin/api-settings',label:'API Settings',icon:Settings}]:links;const current=navigation.find(x=>x.to===location.pathname)?.label||'Workspace';
 return <div className="admin-shell">{open&&<button className="admin-backdrop" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside className={`admin-sidebar ${open?'is-open':''}`}><div className="admin-brand"><div className="admin-brand-image"><BrandLogo/></div><button className="admin-mobile-close" aria-label="Close navigation" onClick={()=>setOpen(false)}><X size={20}/></button></div><p className="admin-nav-label">WORKSPACE</p><nav aria-label="Admin navigation">{navigation.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)} className={({isActive})=>`admin-nav-link ${isActive?'active':''}`}><Icon size={19}/><span>{label}</span><ChevronRight size={15}/></NavLink>)}</nav></aside><div className="admin-body"><header className="admin-topbar"><div className="admin-breadcrumb"><button className="admin-menu" aria-label="Open navigation" aria-expanded={open} onClick={()=>setOpen(!open)}><Menu size={21}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{current}</strong></div><div className="admin-topbar-account"><button className="workspace-refresh" disabled={refreshing} onClick={refresh} aria-label="Refresh page data"><RefreshCw size={17} className={refreshing?'refresh-spinning':''}/><span>{refreshing?'Refreshing...':'Refresh'}</span></button><span className="admin-role">{role}</span><div className="admin-topbar-user"><strong>{user.fullName}</strong><small>{user.email}</small></div><AccountMenu user={user} logout={logout} onUserUpdate={onUserUpdate}/></div></header><main className="admin-content">{children}</main></div></div>;
}
