import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {Users,Radio,Clock,Mic,ClipboardCheck,ArrowUpRight,FileText,Layers,CheckCircle} from 'lucide-react';
import {api} from './api';
import useWorkspaceRefresh from './useWorkspaceRefresh';
export default function AdminDashboard(){
 const[data,setData]=useState(null),[error,setError]=useState(''),[updated,setUpdated]=useState(null);
 useWorkspaceRefresh(async()=>{try{const response=await api.get('/admin/dashboard');setData(response.data);setUpdated(new Date());setError('')}catch(e){setError(e.response?.data?.message||'Unable to load dashboard. Use Refresh to try again.')}});
 const metrics=[['Participants',data?.totalCandidates,Users],['Online now',data?.onlineCandidates,Radio],['Waiting for a partner',data?.queued,Clock],['Active recordings',data?.activeSessions,Mic]];
 return <div className="operations-dashboard"><div className="operations-heading"><div><p className="participant-kicker">OPERATIONS WORKSPACE</p><h1>Dashboard</h1><p>Your participants, recordings and conversation library in one place.</p></div>{updated&&<span className="operations-updated">Updated {updated.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span>}</div>{error&&<p role="alert" className="participant-error">{error}</p>}<div className="operations-metrics">{metrics.map(([label,value,Icon])=><article className="operations-metric" key={label}><span><Icon size={20}/></span><strong>{value??(error?'--':'...')}</strong><p>{label}</p></article>)}</div><div className="operations-columns"><section className="card operations-recent"><div className="operations-section-heading"><h2>Recent recordings</h2><Link to="/admin/reviews">Quality reviews <ArrowUpRight size={15}/></Link></div>{!data?<p className="operations-empty">{error?'Recording data unavailable.':'Loading recording activity...'}</p>:!data.recentSessions.length?<p className="operations-empty">No recordings yet. Sessions will appear here when participants connect.</p>:<div className="operations-session-list">{data.recentSessions.map(session=><article key={session._id}><div className="operations-session-icon"><Mic size={17}/></div><div className="operations-session-info"><strong>{session.project?.name||'Recording session'}</strong><p>{session.candidates?.map(person=>person.fullName||'Participant').join(' & ')||'Participants unavailable'}</p><small>Recording ID: {session._id}</small></div><span className="operations-session-status">{session.status}</span></article>)}</div>}</section><aside className="card operations-summary"><h2>Workspace summary</h2>{[['Awaiting review',data?.pendingReviews,ClipboardCheck],['Approved hours',data?.approvedHours,CheckCircle],['Active projects',data?.projects,Layers],['Enabled topics',data?.enabledTopics,Layers],['Active scripts',data?.scripts,FileText]].map(([label,value,Icon])=><div className="operations-summary-row" key={label}><Icon size={17}/><span>{label}</span><strong>{value??'--'}</strong></div>)}<Link className="btn-primary" to="/admin/candidates">Manage participants <ArrowUpRight size={16}/></Link></aside></div><div className="operations-shortcuts">{[['Topics','Manage conversation topics','/admin/topics',Layers],['Scripts','Upload and manage scripts','/admin/scripts',FileText],['Reviews','Review submitted recordings','/admin/reviews',ClipboardCheck]].map(([title,description,to,Icon])=><Link to={to} className="card" key={to}><Icon size={20}/><div><strong>{title}</strong><p>{description}</p></div><ArrowUpRight size={18}/></Link>)}</div></div>
}
