import BrandLogo from './BrandLogo';
import {nativeApp} from './runtime-config';
import PasswordInput from './PasswordInput';
import React,{useEffect,useState} from 'react';
import {api} from './api';
export default function AuthPage({participantOnly=false}){
 const[passwordLogin,setPasswordLogin]=useState(false);
 const[admin,setAdmin]=useState(false),[identifier,setIdentifier]=useState(''),[challenge,setChallenge]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[remaining,setRemaining]=useState(0),[expiresAt,setExpiresAt]=useState(0),[resendAt,setResendAt]=useState(0),[seconds,setSeconds]=useState(0);
 useEffect(()=>{if(!challenge)return;const tick=()=>{setSeconds(Math.max(0,Math.ceil((expiresAt-Date.now())/1000)));setRemaining(Math.max(0,Math.ceil((resendAt-Date.now())/1000)))};tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[challenge,expiresAt,resendAt]);
 const finish=result=>{if(participantOnly&&result.data.user.role!=='candidate'){setError('This app is for participants only.');return}if(nativeApp&&result.data.refreshToken)localStorage.setItem('participantRefreshToken',result.data.refreshToken);localStorage.setItem('accessToken',result.data.accessToken);location.assign('/')};
 async function send(){if(busy)return;setBusy(true);setError('');try{const result=await api.post('/auth/otp/request',{identifier});setChallenge(result.data.challengeId);setRemaining(result.data.resendAfter);setResendAt(Date.now()+result.data.resendAfter*1000);const deadline=result.data.expiresAt?Date.parse(result.data.expiresAt):Date.now()+result.data.expiresIn*1000;setExpiresAt(deadline);setSeconds(Math.max(0,Math.ceil((deadline-Date.now())/1000)))}catch(failure){setError(failure.response?.status===404?'OTP service is unavailable. Please restart the backend.':failure.response?.data?.message||(!failure.response?'Cannot reach the OTP server. Check your internet and Connection settings.':failure.response.status===429?'Too many requests. Please wait before requesting another OTP.':'OTP delivery failed. Please contact your administrator.'))}finally{setBusy(false)}}
 async function submit(event){event.preventDefault();if(busy)return;if(!admin&&!passwordLogin&&!challenge){await send();return}if(!admin&&!passwordLogin&&Date.now()>=expiresAt){setError('Your code has expired. Please request a new OTP.');return}setBusy(true);setError('');const data=Object.fromEntries(new FormData(event.currentTarget));try{finish(await api.post(admin?'/auth/login':passwordLogin?'/auth/participant-login':'/auth/otp/verify',(admin||passwordLogin)?{identifier,password:data.password,participantOnly,nativeApp}:{challengeId:challenge,code:data.code,nativeApp}))}catch(failure){setError(failure.response?.data?.message||'Unable to sign in. Please try again.')}finally{setBusy(false)}}
 function reset(){setChallenge(null);setRemaining(0);setExpiresAt(0);setResendAt(0);setSeconds(0);setError('')}
 return <main className="auth-page auth-login"><div className="auth-layout"><section className="auth-story"><span className="auth-eyebrow">VOICES THAT POWER AI</span><h1>Human voices.<br/>Intelligent <span>possibilities.</span></h1></section><section className="auth-panel" aria-labelledby="auth-title"><BrandLogo className="auth-brand-logo"/><h2 id="auth-title">{admin?'Admin sign in':passwordLogin?'Participant password login':challenge?'Enter your code':'Participant sign in'}</h2><form onSubmit={submit} className="auth-form"><label htmlFor="identifier">Email or mobile number</label><input required id="identifier" name="identifier" autoComplete="username" value={identifier} disabled={busy||!!challenge} onChange={e=>setIdentifier(e.target.value)} placeholder="Email or mobile with country code"/>{(admin||passwordLogin)?<><label htmlFor="password">Password</label><PasswordInput required disabled={busy} id="password" name="password" autoComplete="current-password" placeholder="Enter your password"/></>:challenge?<><label htmlFor="code">6-digit OTP</label><input key={challenge} disabled={seconds===0} autoFocus required id="code" name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} placeholder="Enter 6-digit code"/></>:null}{error&&<p className="auth-error" role="alert">{error}</p>}<button className="auth-submit" disabled={busy||(!admin&&!passwordLogin&&!!challenge&&seconds===0)}>{busy?'Please wait...':(admin||passwordLogin)?'Sign in':challenge?'Verify OTP & continue':'Send OTP'}</button>{!admin&&!passwordLogin&&challenge&&<div className="otp-actions"><button type="button" disabled={busy||remaining>0} onClick={send}>{remaining>0?'Resend OTP':'Resend OTP'}</button><button type="button" disabled={busy} onClick={reset}>Change email / mobile</button></div>}{!admin&&<button type="button" className="auth-toggle" disabled={busy} onClick={()=>{setPasswordLogin(!passwordLogin);reset()}}>{passwordLogin?'Login with OTP':'Login with User and Password'}</button>}{!participantOnly&&<button type="button" className="auth-toggle" disabled={busy} onClick={()=>{setAdmin(!admin);setPasswordLogin(false);reset()}}>{admin?'Participant OTP login':'Admin / Super Admin login'}</button>}</form></section></div></main>;
}
