import React,{useEffect,useState} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import {api} from './api';
const titles={participants:'Participants',online:'Online participants',waiting:'Waiting for a partner',active:'Active recordings',pending:'Awaiting review',approved:'Approved recordings',projects:'Active projects',session:'Recording details',available:'Available participants'};
export default function DashboardDetails(){
 const {kind}=useParams(),[params,setParams]=useSearchParams();
 const [data,setData]=useState(null),[error,setError]=useState('');
 const search=params.toString();
 useEffect(()=>{let active=true;async function load(){try{const response=await api.get('/admin/dashboard/details/'+kind,{params:Object.fromEntries(new URLSearchParams(search))});if(active){setData(response.data);setError('')}}catch(e){if(active)setError(e.response?.data?.message||'Unable to load details. Use Refresh to try again.')}}setData(null);setError('');load();const refresh=e=>{const task=load();if(e.detail?.tasks)e.detail.tasks.push(task)};window.addEventListener('workspace:refresh',refresh);return()=>{active=false;window.removeEventListener('workspace:refresh',refresh)}},[kind,search]);
 const page=Number(params.get('page'))||1;
 const go=next=>setParams(previous=>{const updated=new URLSearchParams(previous);updated.set('page',next);return updated});
 return <div><Link to="/" className="text-sm text-violet">? Dashboard</Link><h1 className="text-2xl font-bold mt-4 mb-2">{titles[kind]||'Dashboard details'}</h1><p className="text-sm text-slate-500 mb-5">{data?data.total+' records':'Loading records...'}{params.get('language')?' ? '+params.get('language')+' / '+params.get('dialect'):''}</p>{error&&<p role="alert" className="participant-error">{error}</p>}{data?.items.map(item=><article className="card p-5 mb-3" key={item._id}><h2 className="font-bold">{item.user?.fullName||item.fullName||item.name||item.project?.name||'Recording session'}</h2>{(item.user?.email||item.user?.mobile||item.email||item.mobile)&&<p className="text-sm text-slate-500 mt-2">{item.user?.email||item.user?.mobile||item.email||item.mobile}</p>}{item.candidates&&<p className="text-sm mt-2">{item.candidates.map(person=>person.fullName||'Participant').join(' & ')}</p>}<p className="text-sm text-slate-500 mt-2">{item.status||item.user?.status|| (item.active?'Active':'')}{(item.recordingMode||item.user?.recordingMode)&&' ? '+((item.recordingMode||item.user?.recordingMode)==='non_script'?'Non-script':'Script')}{item.language&&' ? '+item.language+' / '+item.dialect}</p>{item.duration!=null&&<p className="text-sm mt-2">Duration: {(item.duration/3600).toFixed(2)} hours</p>}{item.topic&&<p className="text-sm mt-2">Topic: {item.topic.name}</p>}{item.languages&&<p className="text-sm mt-2">{item.languages.map(entry=>entry.language+': '+entry.dialects.join(', ')).join(' ? ')}</p>}{item.guidelines&&<p className="text-sm mt-2 whitespace-pre-wrap">{item.guidelines}</p>}{item.candidates&&<><p className="text-xs text-slate-500 mt-2">Recording ID: {item._id}</p>{kind!=='session'&&<Link className="inline-block text-sm text-violet mt-3" to={'/admin/dashboard/session?id='+item._id}>View recording ?</Link>}{['submitted','assigned'].includes(item.status)&&<Link className="inline-block text-sm text-violet mt-3 ml-4" to="/admin/reviews">Open quality reviews ?</Link>}</>}</article>)}{data&&!data.items.length&&<p className="card p-8 text-center text-slate-500">No records found.</p>}{data&&data.total>20&&<div className="flex items-center gap-4 mt-5"><button className="btn-secondary" disabled={page<=1} onClick={()=>go(page-1)}>Previous</button><span className="text-sm">Page {page} of {Math.ceil(data.total/20)}</span><button className="btn-secondary" disabled={page*20>=data.total} onClick={()=>go(page+1)}>Next</button></div>}</div>
}
