import DownloadPage from './DownloadPage';
import ReviewActions from './ReviewActions';
import ReviewHistory from './ReviewHistory';
import CandidateDirectory from './CandidateDirectory';
import AccessControl from './AccessControl';
import VendorManager from './VendorManager';
import VendorWorkspace from './VendorWorkspace';
import RecordingDownloads from './RecordingDownloads';
import DashboardDetails from './DashboardDetails';
import BrandLogo from './BrandLogo';
import useWorkspaceRefresh from './useWorkspaceRefresh';
import AdminDashboard from './AdminDashboard';
import {serverURL} from './runtime-config';
import TopicManager from './TopicManager';
import ScriptManager from './ScriptManager';
import AccountMenu from './AccountMenu';
import RecordingRoom from './RecordingRoom';
import PairingPage from './PairingPage';
import ParticipantDashboard from './ParticipantDashboard';
import ApiSettings from './ApiSettings';
import AdminShell from './AdminShell';
import AuthPage from './AuthPage';
import React,{createContext,useContext,useEffect,useRef,useState}from 'react';import{createRoot}from'react-dom/client';import{BrowserRouter,Routes,Route,Navigate,useNavigate}from'react-router-dom';import{io}from'socket.io-client';import{api}from './api';import'./index.css';import{Mic,Users,Clock,CheckCircle,LogOut,Radio,ShieldCheck,Volume2,Pause,Play,Square,Send,Wifi,AlertTriangle,LayoutDashboard,FileAudio,ClipboardCheck}from'lucide-react';
const Auth=createContext();const useAuth=()=>useContext(Auth);const status=(s)=> <span className={`badge ${s==='approved'||s==='verified'?'bg-emerald-100 text-emerald-700':s==='rejected'||s==='blocked'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{s}</span>;
function Shell({children,studio=false}){const{user,logout,setUser}=useAuth();const nav=useNavigate();if(['admin','super_admin'].includes(user.role))return <AdminShell user={user} logout={logout} onUserUpdate={setUser}>{children}</AdminShell>;return <div className={`participant-shell${studio?' studio-shell':''}`}><header className="participant-topbar"><div className="participant-topbar-inner"><button onClick={()=>nav('/')} className="flex items-center gap-2 font-bold text-navy"><BrandLogo className="participant-brand-logo"/></button><div className="flex items-center gap-3 text-sm"><span className="account-header-name">{user.fullName&&user.fullName!=='Participant'?user.fullName:(user.email||user.mobile)}</span>{status(user.status)}<AccountMenu user={user} logout={logout} onUserUpdate={setUser}/></div></div></header><main className={`participant-content${studio?' studio-content':''}`}>{children}</main></div>}
function Metric({label,value,icon:Icon}){return <div className="card p-5"><Icon className="mb-3 text-violet"/><p className="text-2xl font-bold">{value}</p><p className="text-sm text-slate-500">{label}</p></div>}
function Dashboard(){const{user}=useAuth();return <Shell>{['admin','super_admin'].includes(user.role)?<AdminDashboard/>:<ParticipantDashboard user={user}/>}</Shell>}
function PairingListener({children}){const{user,setUser}=useAuth();const nav=useNavigate();useEffect(()=>{const t=localStorage.getItem('accessToken');if(!t)return;const s=io(serverURL,{auth:{token:t}});s.on('auth:logout',()=>{localStorage.removeItem('accessToken');setUser(null)});s.on('pair:accepted',x=>nav(`/room/${x.sessionId}?room=${x.roomId}`));return()=>s.close()},[user]);return children}

function Candidates(){const {user}=useContext(Auth);return ['admin','super_admin'].includes(user.role)?<Shell><CandidateDirectory admin/></Shell>:<Navigate to="/"/>}
function Reviews(){const [items,setItems]=useState([]),[error,setError]=useState('');useWorkspaceRefresh(async()=>{try{setItems((await api.get('/reviews')).data);setError('')}catch(e){setError(e.response?.data?.message||'Unable to load reviews.')}});return <Shell><h1 className="text-2xl font-bold mb-5">Quality review queue</h1>{error&&<p className="participant-error">{error}</p>}{items.map(item=><section className="card p-5 mb-4" key={item._id}><h2 className="font-bold">{item.project?.name||'Recording'}</h2><RecordingDownloads sessionId={item._id}/><ReviewActions sessionId={item._id} onDone={()=>setItems(previous=>previous.filter(row=>row._id!==item._id))}/></section>)}<ReviewHistory/></Shell>}
function App(){const[user,setUser]=useState(null);useEffect(()=>{api.get('/me').then(r=>setUser(r.data.user)).catch(()=>{localStorage.removeItem('accessToken');setUser(null)})},[]);const logout=async()=>{await api.post('/auth/logout');localStorage.removeItem('accessToken');setUser(null)};if(user===null&&localStorage.getItem('accessToken'))return <div className="grid min-h-screen place-items-center">Loading...</div>;if(['vendor','reviewer'].includes(user?.role))return <Routes><Route path="*" element={<VendorWorkspace user={user} logout={logout}/>}/></Routes>;return <Auth.Provider value={{user,setUser,logout}}><Routes><Route path="/login" element={<AuthPage/>}/>{user?<Route path="*" element={<PairingListener><Routes><Route path="/" element={<Dashboard/>}/><Route path="/pairing" element={user.role==='candidate'?<Shell><PairingPage/></Shell>:<Navigate to="/"/>}/><Route path="/room/:id" element={<Shell studio><RecordingRoom user={user}/></Shell>}/><Route path="/admin/topics" element={['admin','super_admin'].includes(user.role)?<Shell><TopicManager/></Shell>:<Navigate to="/"/>}/><Route path="/admin/scripts" element={['admin','super_admin'].includes(user.role)?<Shell><ScriptManager/></Shell>:<Navigate to="/"/>}/><Route path="/admin/dashboard/:kind" element={['admin','super_admin'].includes(user.role)?<Shell><DashboardDetails/></Shell>:<Navigate to="/"/>}/><Route path="/admin/quality-team" element={['admin','super_admin'].includes(user.role)?<Shell><VendorManager quality key="quality-team"/></Shell>:<Navigate to="/"/>}/><Route path="/admin/access-control" element={['admin','super_admin'].includes(user.role)?<Shell><AccessControl/></Shell>:<Navigate to="/"/>}/><Route path="/admin/vendors" element={['admin','super_admin'].includes(user.role)?<Shell><VendorManager key="vendors"/></Shell>:<Navigate to="/"/>}/><Route path="/admin/candidates" element={<Candidates/>}/><Route path="/admin/reviews" element={<Reviews/>}/><Route path="/admin/api-settings" element={user.role==='super_admin'?<Shell><ApiSettings/></Shell>:<Navigate to="/"/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></PairingListener>}/>:<Route path="*" element={<Navigate to="/login"/>}/>}</Routes></Auth.Provider>};createRoot(document.getElementById('root')).render(<BrowserRouter><Routes><Route path="/download" element={<DownloadPage/>}/><Route path="*" element={<App/>}/></Routes></BrowserRouter>);
