import DashboardDetails from './DashboardDetails';
import BrandLogo from './BrandLogo';
import useWorkspaceRefresh from './useWorkspaceRefresh';
import AdminDashboard from './AdminDashboard';
import {serverURL} from './runtime-config';
import TopicManager from './TopicManager';
import ScriptManager from './ScriptManager';
import AccountMenu from './AccountMenu';
import RecordingRoom from './RecordingRoom';
import PairingPage from './PairingPage';
import ParticipantDashboard from './ParticipantDashboard';
import ApiSettings from './ApiSettings';
import AdminShell from './AdminShell';
import AuthPage from './AuthPage';
import React,{createContext,useContext,useEffect,useRef,useState}from 'react';import{createRoot}from'react-dom/client';import{BrowserRouter,Routes,Route,Navigate,useNavigate}from'react-router-dom';import{io}from'socket.io-client';import{api}from './api';import'./index.css';import{Mic,Users,Clock,CheckCircle,LogOut,Radio,ShieldCheck,Volume2,Pause,Play,Square,Send,Wifi,AlertTriangle,LayoutDashboard,FileAudio,ClipboardCheck}from'lucide-react';
const Auth=createContext();const useAuth=()=>useContext(Auth);const status=(s)=> <span className={`badge ${s==='approved'||s==='verified'?'bg-emerald-100 text-emerald-700':s==='rejected'||s==='blocked'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{s}</span>;
function Shell({children,studio=false}){const{user,logout,setUser}=useAuth();const nav=useNavigate();if(['admin','super_admin'].includes(user.role))return <AdminShell user={user} logout={logout} onUserUpdate={setUser}>{children}</AdminShell>;return <div className={`participant-shell${studio?' studio-shell':''}`}><header className="participant-topbar"><div className="participant-topbar-inner"><button onClick={()=>nav('/')} className="flex items-center gap-2 font-bold text-navy"><BrandLogo className="participant-brand-logo"/></button><div className="flex items-center gap-3 text-sm"><span className="account-header-name">{user.fullName&&user.fullName!=='Participant'?user.fullName:(user.email||user.mobile)}</span>{status(user.status)}<AccountMenu user={user} logout={logout} onUserUpdate={setUser}/></div></div></header><main className={`participant-content${studio?' studio-content':''}`}>{children}</main></div>}
function Metric({label,value,icon:Icon}){return <div className="card p-5"><Icon className="mb-3 text-violet"/><p className="text-2xl font-bold">{value}</p><p className="text-sm text-slate-500">{label}</p></div>}
function Dashboard(){const{user}=useAuth();return <Shell>{['admin','super_admin'].includes(user.role)?<AdminDashboard/>:<ParticipantDashboard user={user}/>}</Shell>}
function PairingListener({children}){const{user,setUser}=useAuth();const nav=useNavigate();useEffect(()=>{const t=localStorage.getItem('accessToken');if(!t)return;const s=io(serverURL,{auth:{token:t}});s.on('auth:logout',()=>{localStorage.removeItem('accessToken');setUser(null)});s.on('pair:accepted',x=>nav(`/room/${x.sessionId}?room=${x.roomId}`));return()=>s.close()},[user]);return children}

function Candidates(){const[rows,setRows]=useState([]),[notice,setNotice]=useState(''),[failureMessage,setFailureMessage]=useState(''),[saving,setSaving]=useState(null);useWorkspaceRefresh(async()=>{try{const r=await api.get('/admin/candidates');setRows(r.data.items);setFailureMessage('')}catch(e){setFailureMessage(e.response?.data?.message||'Unable to load candidates. Use Refresh to try again.')}});return <Shell><h1 className="mb-6 text-2xl font-bold">Candidate management</h1><p className="mb-4 text-sm text-slate-500">Mode changes apply when the participant joins a new queue. Current sessions keep their original mode.</p>{notice&&<p role="status" className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}{failureMessage&&<p role="alert" className="participant-error">{failureMessage}</p>}<div className="card overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Candidate</th><th>Status</th><th>Recording mode</th><th className="p-4">Action</th></tr></thead><tbody>{rows.map(x=><tr className="border-t" key={x._id}><td className="p-4"><b>{x.fullName}</b><br/><span className="text-slate-500">{x.email||x.mobile}</span></td><td>{status(x.status)}</td><td className="p-4"><select disabled={saving===x._id} aria-label={`Recording mode for ${x.fullName}`} className="rounded-lg border p-2" value={x.recordingMode||'script'} onChange={async e=>{const recordingMode=e.target.value;setSaving(x._id);setNotice('');setFailureMessage('');try{await api.patch(`/admin/candidates/${x._id}`,{recordingMode});setRows(previous=>previous.map(y=>y._id===x._id?{...y,recordingMode}:y));setNotice(`Mode saved for ${x.fullName}. It will apply when they join a new queue.`)}catch(failure){setFailureMessage(failure.response?.data?.message||'Unable to change recording mode')}finally{setSaving(null)}}}><option value="script">Script</option><option value="non_script">Non-script</option></select></td><td className="p-4">{x.status==='pending'?<button onClick={async()=>{await api.patch(`/admin/candidates/${x._id}`,{status:'verified'});setRows(rows.map(y=>y._id===x._id?{...y,status:'verified'}:y))}} className="text-violet font-semibold">Verify</button>:<span className="text-xs text-slate-400">{x.status==='verified'?'Verified':'Unavailable'}</span>}</td></tr>)}</tbody></table></div></Shell>}
function Reviews(){const[items,setItems]=useState([]),[error,setError]=useState('');useWorkspaceRefresh(async()=>{try{const r=await api.get('/reviews');setItems(r.data);setError('')}catch(e){setError(e.response?.data?.message||'Unable to load reviews. Use Refresh to try again.')}});const decide=async(id,decision)=>{await api.post(`/reviews/${id}`,{decision,checklist:{language:true,bothSpeakers:true,noise:true,script:true,duration:true,unique:true},notes:'Reviewed in platform'});setItems(items.filter(x=>x._id!==id))};return <Shell><h1 className="mb-6 text-2xl font-bold">Quality review queue</h1>{error&&<p role="alert" className="participant-error">{error}</p>}{items.length?items.map(s=><div key={s._id} className="card mb-4 p-5"><h2 className="font-bold">{s.project?.name}</h2><p className="my-3 text-sm text-slate-500">Dual channels and metadata available in the review workspace.</p><div className="flex gap-2"><button className="btn-primary" onClick={()=>decide(s._id,'approved')}><CheckCircle/>Approve</button><button className="btn-secondary" onClick={()=>decide(s._id,'revision')}>Request revision</button><button className="btn-secondary" onClick={()=>decide(s._id,'rejected')}>Reject</button></div></div>):<div className="card p-8 text-center text-slate-500"><ClipboardCheck className="mx-auto mb-2"/>No recordings awaiting review.</div>}</Shell>}
function App(){const[user,setUser]=useState(null);useEffect(()=>{api.get('/me').then(r=>setUser(r.data.user)).catch(()=>{localStorage.removeItem('accessToken');setUser(null)})},[]);const logout=async()=>{await api.post('/auth/logout');localStorage.removeItem('accessToken');setUser(null)};if(user===null&&localStorage.getItem('accessToken'))return <div className="grid min-h-screen place-items-center">Loading...</div>;return <Auth.Provider value={{user,setUser,logout}}><Routes><Route path="/login" element={<AuthPage/>}/>{user?<Route path="*" element={<PairingListener><Routes><Route path="/" element={<Dashboard/>}/><Route path="/pairing" element={user.role==='candidate'?<Shell><PairingPage/></Shell>:<Navigate to="/"/>}/><Route path="/room/:id" element={<Shell studio><RecordingRoom user={user}/></Shell>}/><Route path="/admin/topics" element={['admin','super_admin'].includes(user.role)?<Shell><TopicManager/></Shell>:<Navigate to="/"/>}/><Route path="/admin/scripts" element={['admin','super_admin'].includes(user.role)?<Shell><ScriptManager/></Shell>:<Navigate to="/"/>}/><Route path="/admin/dashboard/:kind" element={['admin','super_admin'].includes(user.role)?<Shell><DashboardDetails/></Shell>:<Navigate to="/"/>}/><Route path="/admin/candidates" element={<Candidates/>}/><Route path="/admin/reviews" element={<Reviews/>}/><Route path="/admin/api-settings" element={user.role==='super_admin'?<Shell><ApiSettings/></Shell>:<Navigate to="/"/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></PairingListener>}/>:<Route path="*" element={<Navigate to="/login"/>}/>}</Routes></Auth.Provider>};createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
