import React,{useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Users,ShieldCheck,Radio,ArrowLeft} from 'lucide-react';
import {api} from './api';
export default function PairingPage(){
 const nav=useNavigate();const[state,setState]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[elapsed,setElapsed]=useState(0);
 useEffect(()=>{let stopped=false,timer;const start=Date.now();async function poll(){try{const r=await api.get('/queue/search');if(stopped)return;setState(r.data);setError('');if(r.data.state==='connected'){nav(`/room/${r.data.sessionId}?room=${encodeURIComponent(r.data.roomId)}`,{replace:true});return}}catch(e){if(!stopped)setError(e.response?.data?.message||'Connection interrupted. Retrying automatically.')}if(!stopped)timer=setTimeout(poll,3000)}poll();const clock=setInterval(()=>setElapsed(Math.floor((Date.now()-start)/1000)),1000);return()=>{stopped=true;clearTimeout(timer);clearInterval(clock)}},[nav]);
 async function cancel(){setBusy(true);try{await api.post('/queue/leave');nav('/',{replace:true})}catch(e){setError(e.response?.data?.message||'Unable to leave the queue. Please try again.')}finally{setBusy(false)}}
 return <section className="pairing-page"><span className="participant-kicker">LIVE PARTICIPANT MATCHING</span><div className="pairing-radar" aria-hidden="true"><i/><i/><span><Users size={34}/></span></div><h1>{state?.state==='offline'?'You are not in the queue':'Finding your recording partner'}</h1><p>{state?.state==='offline'?'Select a project and go online to start matching.':'We are looking for an available participant with the same project, language and dialect. You will connect automatically when a partner is ready.'}</p>{state?.state!=='offline'&&<div className="pairing-search" role="status"><Radio size={16}/>Searching for an available participant<span>{Math.floor(elapsed/60)}:{String(elapsed%60).padStart(2,'0')}</span></div>}{state?.project&&<div className="pairing-details"><div><small>PROJECT</small><strong>{state.project.name}</strong></div><div><small>LANGUAGE & DIALECT</small><strong>{state.language} / {state.dialect}</strong></div></div>}{error&&<p className="participant-error" role="alert">{error}</p>}<div className="pairing-consent"><ShieldCheck size={18}/>Both participants consent before recording starts.</div><button className="btn-secondary" disabled={busy} onClick={state?.state==='offline'?()=>nav('/'):cancel}><ArrowLeft size={16}/>{busy?'Leaving…':state?.state==='offline'?'Back to workspace':'Cancel search'}</button></section>;
}
