import {useNavigate} from 'react-router-dom';
import React,{useEffect,useState} from 'react';
import {Mic,Radio,Clock,FileAudio,ArrowUpRight,ChevronRight,ShieldCheck,LayoutDashboard,Layers,Headphones,CheckCircle} from 'lucide-react';
import {api} from './api';
import AvailabilityCounts from './AvailabilityCounts';
export default function ParticipantDashboard({user}){
 const nav=useNavigate();const[topics,setTopics]=useState([]);useEffect(()=>{let active=true;const refresh=()=>api.get('/topics').then(r=>{if(active)setTopics(r.data)}).catch(()=>{});refresh();const timer=setInterval(refresh,15000);return()=>{active=false;clearInterval(timer)}},[]);
 const[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[section,setSection]=useState('overview'),[form,setForm]=useState({project:'',language:'',dialect:''}),[consentGiven,setConsentGiven]=useState(false);
 async function load(){try{setData((await api.get('/dashboard/candidate')).data);setError('')}catch(e){setError(e.response?.data?.message||'Unable to load your workspace. Please try again.')}}
 useEffect(()=>{load()},[]);
 const project=data?.projects?.find(p=>p._id===form.project),language=project?.languages?.find(x=>x.language===form.language),queue=data?.queue;
 async function toggle(){if(busy)return;if(!queue&&(!form.project||!form.language||!form.dialect)){setError('Please select a project, language and dialect.');return}if(!queue&&!data?.profile?.consent&&!consentGiven){setError('Please give recording consent before going online.');return}setBusy(true);setError('');try{if(queue)await api.post('/queue/leave');else {if(!data.profile?.consent){const saved=await api.patch('/me',{consent:true});if(saved.data?.consent!==true)throw Error('Consent was not saved');setData(previous=>({...previous,profile:{...previous.profile,consent:true}}))}await api.post('/queue/join',{...form,recordingType:project?.recordingType||'dual'});nav('/pairing')};await load()}catch(e){if(e.response?.data?.sessionId){nav(`/room/${e.response.data.sessionId}?room=${encodeURIComponent(e.response.data.roomId)}`)}else setError(e.response?.data?.message||'Unable to update availability.')}finally{setBusy(false)}}
 function navigate(id){setSection(id);document.getElementById('participant-'+id)?.scrollIntoView({behavior:'smooth',block:'start'})}
 const metrics=[{label:'Availability',value:queue?'In queue':'Offline',icon:Radio},{label:'Recordings',value:data?.summary?.totalRecordings??'—',icon:FileAudio},{label:'Hours submitted',value:data?.profile?.submittedHours??'—',icon:Clock}];
 return <div className="participant-dashboard"><section id="participant-overview" className="participant-welcome"><div><p className="participant-kicker">YOUR RECORDING WORKSPACE</p><h1>Let's make your voice count.</h1><p>{user.recordingMode==='non_script'?'Non-script mode - natural conversations':user.recordingMode==='script'?'Script mode - guided conversations':'Manage your sessions, projects and recording activity.'}</p></div><span className="participant-id">{data?.profile?.candidateId||'Participant'}</span></section>{error&&<div className="participant-error" role="alert">{error}{!data&&<button onClick={load}>Retry</button>}</div>}
 <section className="participant-hero"><div className="participant-hero-top"><span className="participant-live"><span/>{queue?'PAIRING IN PROGRESS':'RECORDING STUDIO'}</span><span className="participant-hero-icon"><Mic size={22}/></span></div><h2>{queue?'Finding your conversation partner':'Your next conversation starts here.'}</h2><p>{queue?'Keep this workspace open. We will notify you when a compatible partner is available.':'Choose a project and your language preferences to join a recording session.'}</p><button onClick={()=>queue?nav('/pairing'):navigate('projects')} disabled={busy} className="participant-hero-action">{queue?'Open waiting room':'Explore projects'}<ArrowUpRight size={17}/></button><div className="participant-wave" aria-hidden="true">{Array.from({length:24},(_,i)=><i key={i} style={{height:12+((i*17)%48)}}/>)}</div></section>
 <div className="participant-metrics">{metrics.map(({label,value,icon:Icon})=><div key={label} className="participant-metric"><span><Icon size={18}/></span><strong>{value}</strong><p>{label}</p></div>)}</div>
 {user.status!=='verified'&&<div className="participant-verification"><ShieldCheck size={20}/><div><strong>{user.status==='pending'?'Account review in progress':'Account verification required'}</strong><p>You can explore projects while your account is reviewed. Recording unlocks after verification.</p></div></div>}
 <div className="participant-columns"><section id="participant-projects" className="participant-section"><div className="participant-section-heading"><div><span className="participant-kicker">GET STARTED</span><h2>Pairing preferences</h2></div><Headphones size={21}/></div><form onSubmit={e=>{e.preventDefault();toggle()}}><fieldset disabled={!!queue||busy} className="participant-preferences"><div><label htmlFor="pair-project">Project</label><select id="pair-project" required value={form.project} onChange={e=>setForm({project:e.target.value,language:'',dialect:''})}><option value="">Select a project</option>{data?.projects?.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select></div><div className="participant-select-row"><div><label htmlFor="pair-language">Language</label><select id="pair-language" required disabled={!project} value={form.language} onChange={e=>setForm({...form,language:e.target.value,dialect:''})}><option value="">Select language</option>{project?.languages?.map(l=><option key={l.language}>{l.language}</option>)}</select></div><div><label htmlFor="pair-dialect">Dialect</label><select id="pair-dialect" required disabled={!language} value={form.dialect} onChange={e=>setForm({...form,dialect:e.target.value})}><option value="">Select dialect</option>{language?.dialects?.map(d=><option key={d}>{d}</option>)}</select></div></div>{!data?.profile?.consent&&<label className="participant-consent"><input type="checkbox" checked={consentGiven} onChange={e=>setConsentGiven(e.target.checked)}/><span>I consent to audio recording and quality review for this platform.</span></label>}</fieldset><button className="participant-primary" type={queue?'button':'submit'} onClick={queue?toggle:undefined} disabled={busy||!data||(!queue&&(user.status!=='verified'||(!data.profile?.consent&&!consentGiven)))}><Radio size={17}/>{busy?'Please wait…':queue?'Leave queue':'Go online'}<ChevronRight size={16}/></button>{data?.profile?.consent&&<p className="participant-hint">Recording consent saved.</p>}</form><AvailabilityCounts participant selection={queue?{project:queue.project?._id||queue.project,language:queue.language,dialect:queue.dialect}:form}/><div className="participant-project-list"><div className="participant-list-heading"><h3>Available projects</h3><span>{data?.projects?.length??0}</span></div>{data?.projects?.length?data.projects.map(p=><button key={p._id} className="participant-project" disabled={!!queue} onClick={()=>setForm({project:p._id,language:'',dialect:''})}><span className="participant-project-icon"><Layers size={18}/></span><span><strong>{p.name}</strong><small>{p.recordingType==='dual'?'Dual speaker':'Single speaker'} · {p.targetHours||0} target hours</small></span><ChevronRight size={17}/></button>):<p className="participant-empty">{data?'No active projects yet.':'Loading projects…'}</p>}</div></section>
 <section id="participant-recordings" className="participant-section"><div className="participant-section-heading"><div><span className="participant-kicker">YOUR ACTIVITY</span><h2>Recent recordings</h2></div><FileAudio size={21}/></div>{data?.sessions?.length?<div className="participant-recordings">{data.sessions.map(s=><div key={s._id} className="participant-recording"><span className="participant-project-icon"><FileAudio size={18}/></span><div><strong>{s.project?.name||'Recording session'}</strong><p className="participant-recording-id"><span>Recording ID</span><code>{s._id}</code></p><p className="participant-recording-partners">{(s.candidates||[]).map((candidate,index)=><span key={candidate?._id||index}>{candidate?.fullName&&candidate.fullName!=='Participant'?candidate.fullName:'Name not added'}{String(candidate?._id)===String(user._id)?' (You)':''}</span>)}</p><small>{Math.round((s.duration||0)/60)} min · {new Date(s.createdAt).toLocaleDateString()}</small></div><span className={`participant-session-status ${s.status==='approved'?'approved':''}`}>{s.status}</span></div>)}</div>:<div className="participant-empty-state"><span><Headphones size={28}/></span><h3>{data?'Your recording journey starts here':'Loading your activity'}</h3><p>{data?'Completed sessions will appear here. Pick a project to get started.':'Your workspace will be ready shortly.'}</p>{data&&<button onClick={()=>navigate('projects')}>Browse projects<ChevronRight size={15}/></button>}</div>}<div className="participant-quality"><CheckCircle size={17}/><span>Every conversation contributes to better speech data.</span></div></section></div>
 <nav className="participant-bottom-nav" aria-label="Participant navigation">{[['overview','Overview',LayoutDashboard],['projects','Projects',Layers],['recordings','Recordings',Headphones]].map(([id,label,Icon])=><button key={id} onClick={()=>navigate(id)} className={section===id?'active':''} aria-current={section===id?'page':undefined}><Icon size={20}/><span>{label}</span></button>)}</nav></div>;
}
