import {detectMicrophone,microphoneError} from './microphone';
import {serverURL} from './runtime-config';
import TopicDropdown from './TopicDropdown';
import React,{useEffect,useRef,useState} from 'react';import {useParams} from 'react-router-dom';import {io} from 'socket.io-client';import {Mic,Pause,Play,Square,MicOff,FileText,UploadCloud,Wifi} from 'lucide-react';import {api} from './api';
export default function RecordingRoom({user}){
 const {id}=useParams();const[session,setSession]=useState(null),[control,setControl]=useState({state:'idle',elapsedMs:0,changedAt:null,muted:false}),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[level,setLevel]=useState(0),[seconds,setSeconds]=useState(0),[recording,setRecording]=useState(null),[uploading,setUploading]=useState(false),[submitted,setSubmitted]=useState(false),[submissionMessage,setSubmissionMessage]=useState(''),[muted,setMuted]=useState(false);
 const[submissionRequested,setSubmissionRequested]=useState(false);const uploadLockRef=useRef(false),uploadRef=useRef(),submissionCompleteRef=useRef(false);
 const[micStatus,setMicStatus]=useState('detecting'),[micLabel,setMicLabel]=useState('Detecting microphone'),[micRetry,setMicRetry]=useState(0);
 const recordingMode=session?.recordingMode||user.recordingMode;const nonScript=recordingMode==='non_script';
 const[topics,setTopics]=useState([]),[topicState,setTopicState]=useState({topic:null,approvedBy:[],version:0});const topicVersionRef=useRef(-1);const topicReady=!!topicState.topic&&topics.some(t=>t._id===String(topicState.topic._id))&&(nonScript||!!session?.script);function applyTopic(state){if(state.version<topicVersionRef.current)return;topicVersionRef.current=state.version;setTopicState(state);if(Object.prototype.hasOwnProperty.call(state,'script'))setSession(previous=>previous?{...previous,script:state.script}:previous)}
 useEffect(()=>{let active=true;const refresh=()=>api.get('/topics').then(r=>{if(active)setTopics(r.data)}).catch(()=>{});refresh();const timer=setInterval(refresh,15000);return()=>{active=false;clearInterval(timer)}},[]);
 async function chooseTopic(topicId){setBusy(true);setError('');try{applyTopic((await api.post(`/sessions/${id}/topic`,{topicId})).data)}catch(failure){setError(failure.response?.data?.message||'Unable to update topic.')}finally{setBusy(false)}}
 const streamRef=useRef(),recorderRef=useRef(),versionRef=useRef(-1),uploadedRef=useRef(false),applyRef=useRef();
 applyRef.current=state=>{if(state.version<=versionRef.current)return;versionRef.current=state.version;setControl(state);const stream=streamRef.current;if(!stream)return;try{let recorder=recorderRef.current;if(['recording','paused'].includes(state.state)&&(!recorder||recorder.state==='inactive')){const mimeType=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(type=>MediaRecorder.isTypeSupported(type));recorder=new MediaRecorder(stream,mimeType?{mimeType}:undefined);recorderRef.current=recorder;const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunks,{type:recorder.mimeType});if(!blob.size){setError('Recording is empty. Please record again.');return}setRecording(blob)};recorder.start(1000)}if(state.state==='paused'&&recorder?.state==='recording')recorder.pause();if(state.state==='recording'&&recorder?.state==='paused')recorder.resume();if(state.state==='stopped'&&recorder&&recorder.state!=='inactive')recorder.stop()}catch{setError('Your recorder could not apply the shared action. Check microphone permissions and browser support.')}};
 useEffect(()=>{let disposed=false,socket,peer,audioContext,meterFrame,remoteAudio;const ice=[];async function init(){setMicStatus('detecting');setMicLabel('Detecting microphone');setConnected(false);try{const data=(await api.get(`/sessions/${id}`)).data;if(disposed)return;setSession(data);applyTopic({topic:data.topic,approvedBy:data.topicApprovedBy||[],version:data.topicVersion||0});const detected=await detectMicrophone();const stream=detected.stream;if(disposed){stream.getTracks().forEach(t=>t.stop());return}streamRef.current=stream;setMicStatus('ready');setMuted(false);setLevel(0);setMicLabel(detected.label);stream.getAudioTracks().forEach(track=>{track.onended=()=>{if(!disposed){setMicStatus('unavailable');setMicLabel('Microphone disconnected');setConnected(false);setError('Microphone disconnected. Reconnect it and tap Retry microphone after stopping your recording.')}}});audioContext=new AudioContext();const analyser=audioContext.createAnalyser();audioContext.createMediaStreamSource(stream).connect(analyser);const values=new Uint8Array(analyser.fftSize);const meter=()=>{analyser.getByteTimeDomainData(values);let min=255,max=0;for(const value of values){min=Math.min(min,value);max=Math.max(max,value)}setLevel(Math.min(100,max-min));meterFrame=requestAnimationFrame(meter)};meter();peer=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});stream.getTracks().forEach(track=>peer.addTrack(track,stream));socket=io(serverURL,{auth:callback=>callback({token:localStorage.getItem('accessToken')})});const roomId=data.roomId;
 socket.on('connect',()=>socket.emit('room:join',{roomId}));socket.on('disconnect',()=>{setConnected(false);setError('Connection interrupted. Reconnecting…')});socket.on('connect_error',()=>setError('Unable to connect to the recording room. Refresh after checking your connection.'));socket.on('room:error',event=>setError(event.message));socket.on('session:ended',event=>{setConnected(false);setError(event.message);stream.getTracks().forEach(track=>track.stop());peer?.close();remoteAudio?.pause()});socket.on('recording:submission-requested',event=>{if(event.sessionId===id){setSubmissionRequested(true);uploadRef.current?.()}});socket.on('recording:submitted',()=>{submissionCompleteRef.current=true;setSubmitted(true);setRecording(null);setSubmissionMessage('Both recordings submitted successfully.')});socket.on('topic:state',applyTopic);socket.on('recording:state',state=>applyRef.current(state));socket.on('room:ready',async()=>{if(disposed)return;setError('');if(String(data.candidates[0])===String(user._id)&&peer.signalingState==='stable'){await peer.setLocalDescription(await peer.createOffer());socket.emit('webrtc:signal',{roomId,signal:peer.localDescription})}});
 socket.on('webrtc:signal',async({signal})=>{try{if(signal.type==='offer'||signal.type==='answer'){await peer.setRemoteDescription(signal);while(ice.length)await peer.addIceCandidate(ice.shift());if(signal.type==='offer'){await peer.setLocalDescription(await peer.createAnswer());socket.emit('webrtc:signal',{roomId,signal:peer.localDescription})}}else if(signal.candidate){if(peer.remoteDescription)await peer.addIceCandidate(signal.candidate);else ice.push(signal.candidate)}}catch{setError('Audio connection failed. Please check your network and refresh.')}});
 peer.onicecandidate=event=>event.candidate&&socket.emit('webrtc:signal',{roomId,signal:{candidate:event.candidate}});peer.onconnectionstatechange=()=>{setConnected(peer.connectionState==='connected');if(peer.connectionState==='failed')setError('Audio connection failed. A TURN server may be needed on this network.')};peer.ontrack=event=>{remoteAudio=new Audio();remoteAudio.srcObject=event.streams[0];remoteAudio.autoplay=true;remoteAudio.play().catch(()=>setError('Allow audio playback in your browser to hear your partner.'))};
 }catch(failure){if(!disposed){if(!streamRef.current){setMicStatus('unavailable');setMicLabel('Microphone unavailable')}setError(failure.response?(failure.response.data?.message||'Unable to load the studio. Please refresh and try again.'):['NotAllowedError','NotFoundError','NotReadableError','AbortError','NotSupportedError','OverconstrainedError'].includes(failure.name)?microphoneError(failure):'Unable to connect to the studio. Check your connection and try again.')}}}init();return()=>{disposed=true;cancelAnimationFrame(meterFrame);if(recorderRef.current&&recorderRef.current.state!=='inactive'){recorderRef.current.onstop=null;recorderRef.current.stop()}streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;socket?.close();peer?.close();audioContext?.close();remoteAudio?.pause();}},[id,user._id,micRetry]);
 useEffect(()=>{const tick=()=>setSeconds(Math.floor((control.elapsedMs+(control.state==='recording'?Math.max(0,Date.now()-control.changedAt):0))/1000));tick();const timer=setInterval(tick,250);return()=>clearInterval(timer)},[control]);
 async function action(action){if(busy)return;setBusy(true);setError('');try{const result=await api.post(`/sessions/${id}/control`,{action});applyRef.current(result.data.control)}catch(failure){setError(failure.response?.data?.message||'Unable to update recording controls.')}finally{setBusy(false)}}
 async function submitRecording(){if(uploadLockRef.current||!recording||submitted)return;uploadLockRef.current=true;setUploading(true);setError('');setSubmissionMessage('Uploading to cloud. Keep this screen open.');try{if(!uploadedRef.current){const signed=(await api.post('/uploads/presign',{sessionId:id,contentType:recording.type})).data;const response=await fetch(signed.url,{method:'PUT',headers:{'Content-Type':recording.type},body:recording});if(!response.ok)throw Error('Cloud upload failed. Check your connection and try Submit again.');await api.post('/sessions/'+id+'/files',{key:signed.key,mimeType:recording.type,size:recording.size});uploadedRef.current=true}const result=await api.post('/sessions/'+id+'/submit');if(!result.data.pending){submissionCompleteRef.current=true;setSubmitted(true);setRecording(null)}if(!result.data.pending||!submissionCompleteRef.current)setSubmissionMessage(result.data.message)}catch(failure){setSubmissionMessage('');setError(failure.response?.data?.message||failure.message||'Upload failed. Retry Submit recording.')}finally{uploadLockRef.current=false;setUploading(false)}}

 uploadRef.current=submitRecording;
 async function requestSubmission(){if(uploadLockRef.current)return;setBusy(true);setError('');try{const result=await api.post('/sessions/'+id+'/submission-request');if(result.data.submitted){submissionCompleteRef.current=true;setSubmitted(true);setRecording(null);setSubmissionMessage(result.data.message)}else{setSubmissionRequested(true);uploadRef.current?.()}}catch(failure){setError(failure.response?.data?.message||'Unable to request submission. Try again.')}finally{setBusy(false)}}
 useEffect(()=>{if(submissionRequested&&recording&&!submitted&&!uploadedRef.current)uploadRef.current?.()},[submissionRequested,recording,submitted]);
 useEffect(()=>{if(control.state!=='stopped'||submitted)return;let active=true;const check=async()=>{try{const {data}=await api.get('/sessions/'+id+'/submission-status');if(!active)return;if(data.submitted){submissionCompleteRef.current=true;setSubmitted(true);setRecording(null);setSubmissionMessage('Both recordings submitted successfully.')}else if(data.requested)setSubmissionRequested(true)}catch{}};check();const timer=setInterval(check,4000);return()=>{active=false;clearInterval(timer)}},[id,control.state,submitted]);
 useEffect(()=>{if(!recording||submitted)return;const warn=e=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[recording,submitted]);
 function toggleMute(){if(!streamRef.current)return;const next=!muted;streamRef.current.getAudioTracks().forEach(track=>{track.enabled=!next});setMuted(next)}
 return <div className="studio-room">
 <header className="studio-heading"><div><p className="studio-eyebrow">RECORDING STUDIO</p><h1>{session?.project?.name||'Loading studio...'}</h1></div><span className={`studio-connection ${connected?'is-connected':''}`}><Wifi size={14}/>{connected?'Connected':'Connecting'}</span></header>
 {error&&<p className="studio-error" role="alert">{error}{micStatus==='unavailable'&&<button disabled={['recording','paused'].includes(control.state)} className="btn-secondary mt-2" onClick={()=>{versionRef.current=-1;setError('');setMicRetry(value=>value+1)}}>Retry microphone</button>}</p>}
 <div className="studio-layout">
 <section className="studio-console" aria-label="Recording controls">
 <div className="studio-session-status"><span className={`studio-status-dot ${control.state==='recording'?'is-live':''}`}/><h2>{control.state==='idle'?(connected?(topicReady?'Ready to record':'Choose a topic together'):'Waiting for partner audio'):control.state==='paused'?'Recording paused':control.state==='stopped'?'Session complete':'Recording live'}</h2><TopicDropdown iconOnly topics={topics} value={topicState.topic?._id||''} disabled={busy||control.state!=='idle'||!session} onChange={chooseTopic}/></div>{topicState.topic&&<div className="studio-topic-chip"><FileText size={12}/><span>{topicState.topic.name}</span></div>}
 <div className="studio-timer" aria-label="Recording duration">{String(Math.floor(seconds/60)).padStart(2,'0')}<span>:</span>{String(seconds%60).padStart(2,'0')}</div>
 <div className="studio-mic"><div className="studio-mic-label">{muted?<MicOff size={16}/>:<Mic size={16}/>}<span>{micStatus==='ready'?(muted?'Your mic is muted':micLabel):micLabel}</span><span className="studio-mic-state">{micStatus!=='ready'?(micStatus==='detecting'?'Detecting':'Unavailable'):muted?'Muted':'Active'}</span></div><div className="studio-meter" aria-hidden="true">{Array.from({length:28},(_,i)=><span key={i} className={!muted&&level>i*3?'is-active':''}/>)}</div></div>
 <div className="studio-actions">
 {control.state==='idle'&&<button disabled={busy||!connected||!topicReady||micStatus!=='ready'} onClick={()=>action('start')} className="studio-button studio-start"><Mic size={18}/>Start recording</button>}
 {['recording','paused'].includes(control.state)&&<><button disabled={busy} onClick={()=>action(control.state==='paused'?'resume':'pause')} className="studio-button studio-resume">{control.state==='paused'?<Play size={18}/>:<Pause size={18}/>} {control.state==='paused'?'Resume':'Pause'}</button><button disabled={busy} onClick={()=>action('stop')} className="studio-button studio-stop"><Square size={16}/>Stop</button></>}
 {control.state!=='stopped'&&<button disabled={busy} onClick={toggleMute} className="studio-button studio-mute" aria-label={muted?'Unmute my microphone':'Mute my microphone'} aria-pressed={muted} title={muted?'Unmute my mic':'Mute my mic'}>{muted?<MicOff size={20}/>:<Mic size={20}/>}</button>}
 {recording&&!submitted&&<button className="studio-button studio-start" disabled={uploading||busy} onClick={requestSubmission}><UploadCloud size={18}/>{uploading?'Uploading...':'Submit recording'}</button>}
 {submissionMessage&&<p role="status" className="studio-submission-status">{submissionMessage}</p>}
 </div>
 </section>
 <section className="studio-script"><header className="studio-script-heading"><span className="studio-script-icon"><FileText size={18}/></span><div><h2>{nonScript?'Non-script conversation':recordingMode==='script'?'Conversation script':'Conversation'}</h2><p>{nonScript?'Speak naturally with your partner':recordingMode==='script'?'Follow speaker turns with your partner':'Loading your recording mode'}</p></div>{topicState.topic&&<span className="studio-script-topic">{topicState.topic.name}</span>}</header><div className="studio-script-scroll" tabIndex={0} role="region" aria-label="Scrollable conversation script"><pre>{nonScript?(topicState.topic?.name?'Topic: '+topicState.topic.name+'\n\n':'')+'Have a natural conversation in your selected language and dialect. Take turns speaking and give your partner time to respond.':topicState.topic?(session?.script?.content||'No script uploaded for this topic yet.'): 'Select a topic to view its conversation script.'}</pre></div><footer className="studio-script-footer">Read naturally. Give your partner time to respond.</footer></section>
 </div></div>;
}
