import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';import {createPortal} from 'react-dom';import {ChevronDown,Search,Check,Layers,X} from 'lucide-react';
export default function TopicDropdown({topics,value,disabled,onChange,iconOnly=false}){
 const[open,setOpen]=useState(false),[query,setQuery]=useState(''),[position,setPosition]=useState(null);const trigger=useRef(),popup=useRef(),search=useRef();const selected=topics.find(t=>t._id===value),filtered=topics.filter(t=>t.name.toLowerCase().includes(query.trim().toLowerCase()));
 const close=()=>{setOpen(false);trigger.current?.focus()};
 useLayoutEffect(()=>{if(!open)return;const place=()=>{const r=trigger.current.getBoundingClientRect(),viewport=window.visualViewport,height=viewport?.height||window.innerHeight,offset=viewport?.offsetTop||0,width=Math.min(Math.max(r.width,280),window.innerWidth-24),below=height+offset-r.bottom-12,above=r.top-offset-12,up=below<220&&above>below,available=Math.max(100,up?above:below);setPosition({left:Math.max(12,Math.min(r.left,window.innerWidth-width-12)),width,maxHeight:Math.min(320,available),...(up?{bottom:window.innerHeight-r.top+8}:{top:r.bottom+8})})};place();window.addEventListener('resize',place);window.visualViewport?.addEventListener('resize',place);return()=>{window.removeEventListener('resize',place);window.visualViewport?.removeEventListener('resize',place)}},[open]);
 useEffect(()=>{if(!open)return;search.current?.focus();const outside=e=>{if(!popup.current?.contains(e.target)&&!trigger.current?.contains(e.target))setOpen(false)};const key=e=>{if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='ArrowDown'||e.key==='ArrowUp'){const items=[...popup.current.querySelectorAll('.topic-option')];if(!items.length)return;e.preventDefault();let index=items.indexOf(document.activeElement);index=e.key==='ArrowDown'?(index+1)%items.length:(index<=0?items.length-1:index-1);items[index].focus()}if(e.key==='Tab'){const items=[...popup.current.querySelectorAll('input,button')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',key)}},[open]);
 useEffect(()=>{if(disabled)setOpen(false)},[disabled]);
 return <><button ref={trigger} type="button" id="studio-topic" className={iconOnly?'topic-dropdown-trigger topic-icon-trigger':'topic-dropdown-trigger'} aria-label={'Conversation topic: '+(selected?.name||'Choose a topic')} aria-haspopup="dialog" aria-expanded={open} aria-controls={open?'topic-dropdown-panel':undefined} disabled={disabled} onClick={()=>{setQuery('');setOpen(!open)}}><Layers size={iconOnly?19:16}/>{!iconOnly&&<><span>{selected?.name||'Choose a topic'}</span><ChevronDown size={16} className={open?'is-open':''}/></>}</button>{open&&createPortal(<div ref={popup} id="topic-dropdown-panel" role="dialog" aria-label="Choose conversation topic" className="topic-dropdown-panel" style={position||{visibility:'hidden'}}><div className="topic-dropdown-title"><strong>Choose a topic</strong><button type="button" aria-label="Close topic list" onClick={close}><X size={16}/></button></div><div className="topic-dropdown-search"><Search size={16}/><input ref={search} aria-label="Search topics" placeholder="Search topics..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="topic-dropdown-options">{filtered.map(topic=><button type="button" key={topic._id} className={'topic-option'+(topic._id===value?' selected':'')} aria-pressed={topic._id===value} onClick={()=>{close();onChange(topic._id)}}><span>{topic.name}</span>{topic._id===value&&<Check size={16}/>}</button>)}{!filtered.length&&<p className="topic-dropdown-empty">{topics.length?'No topics match your search.':'No enabled topics available.'}</p>}</div></div>,document.body)}</>
}
