import React,{useState} from 'react';
import {api} from './api';
import useWorkspaceRefresh from './useWorkspaceRefresh';
export default function VendorLink(){
 const [data,setData]=useState(null),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){try{setData((await api.get('/me/vendor')).data);setError('')}catch(e){setError(e.response?.data?.message||'Unable to load vendor link.')}}useWorkspaceRefresh(load);
 async function link(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{const response=await api.post('/me/vendor',{vendorCode:code});setData({vendor:response.data.vendor});setMessage(response.data.message)}catch(e){setError(e.response?.data?.issues?.[0]?.message||e.response?.data?.message||'Unable to link vendor.')}finally{setBusy(false)}}
 return <section className="card p-5 mb-5" aria-labelledby="vendor-link-heading"><h2 id="vendor-link-heading" className="font-bold text-lg mb-3">Vendor link</h2>{error&&<p className="participant-error" role="alert">{error}<button type="button" onClick={load}>Retry</button></p>}{message&&<p role="status" className="text-sm text-emerald-700 mb-3">{message}</p>}{data?.vendor?<><p className="font-semibold">{data.vendor.fullName}</p><p className="font-mono text-sm mt-2">{data.vendor.vendorCode}</p><p className="text-sm text-slate-500 mt-2">Your candidate account is linked to this vendor.</p></>:data?<form onSubmit={link}><label className="text-sm" htmlFor="dashboard-vendor-code">Vendor code (optional)</label><div className="flex flex-wrap items-center gap-3 mt-2"><input className="field" style={{maxWidth:420}} id="dashboard-vendor-code" required maxLength={28} disabled={busy} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="VND-..."/><button className="btn-primary" disabled={busy||!code.trim()}>{busy?'Linking...':'Link vendor'}</button></div><p className="text-sm text-slate-500 mt-3">Enter your vendor's code to appear in their candidate list. You can link your account once.</p></form>:!error&&<p role="status">Loading vendor link...</p>}</section>
}
